name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive
            - name: Build libpg_query
              run: |
                  make -C third_party/libpg_query
            - name: Install Clang 18
              run: |
                  wget https://apt.llvm.org/llvm.sh
                  chmod +x llvm.sh
                  sudo ./llvm.sh 18
                  sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-18 100
                  sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-18 100

            - name: Install CMake & Ninja
              run: |
                  sudo apt-get update
                  sudo apt-get install -y cmake ninja-build

            - name: Configure
              run: >
                  cmake -S . -B build -G Ninja
                  -DCMAKE_CXX_COMPILER=clang++-18
                  -DCMAKE_BUILD_TYPE=Debug

            - name: Build
              run: cmake --build build

            - name: Test
              run: ctest --test-dir build --output-on-failure
